const GET_ALL_USERS = "SELECT * FROM user"
const GET_USER_BY_EMAIL = "SELECT * FROM user WHERE email = ?"
const GET_USER_BY_USERNAME = "SELECT * FROM user WHERE username = ?"
const CREATE_NEW_USER = "INSERT INTO user SET ?"
const UPDATE_USER_STATUS =  "UPDATE user SET status = 'active' WHERE id = ?"
const GET_USER_BY_CONFIRMATION_CODE = "SELECT * FROM user WHERE confirmationcode = ?"
const DELETE_USER_CONFIRMATION_CODE = "UPDATE user SET confirmationcode = null WHERE id = ?"
module.exports = {GET_ALL_USERS,GET_USER_BY_EMAIL,CREATE_NEW_USER,UPDATE_USER_STATUS,GET_USER_BY_CONFIRMATION_CODE,GET_USER_BY_USERNAME,DELETE_USER_CONFIRMATION_CODE}